/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignupIndexRouteImport } from './routes/signup/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as DashboardLayoutDashboardIndexRouteImport } from './routes/_dashboard-layout/dashboard/index'
import { Route as DashboardLayoutProjectIdIndexRouteImport } from './routes/_dashboard-layout/project/$id/index'

const DashboardLayoutLazyRouteImport = createFileRoute('/_dashboard-layout')()

const DashboardLayoutLazyRoute = DashboardLayoutLazyRouteImport.update({
  id: '/_dashboard-layout',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/_dashboard-layout.lazy').then((d) => d.Route),
)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupIndexRoute = SignupIndexRouteImport.update({
  id: '/signup/',
  path: '/signup/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLayoutDashboardIndexRoute =
  DashboardLayoutDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => DashboardLayoutLazyRoute,
  } as any)
const DashboardLayoutProjectIdIndexRoute =
  DashboardLayoutProjectIdIndexRouteImport.update({
    id: '/project/$id/',
    path: '/project/$id/',
    getParentRoute: () => DashboardLayoutLazyRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginIndexRoute
  '/signup': typeof SignupIndexRoute
  '/dashboard': typeof DashboardLayoutDashboardIndexRoute
  '/project/$id': typeof DashboardLayoutProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginIndexRoute
  '/signup': typeof SignupIndexRoute
  '/dashboard': typeof DashboardLayoutDashboardIndexRoute
  '/project/$id': typeof DashboardLayoutProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dashboard-layout': typeof DashboardLayoutLazyRouteWithChildren
  '/login/': typeof LoginIndexRoute
  '/signup/': typeof SignupIndexRoute
  '/_dashboard-layout/dashboard/': typeof DashboardLayoutDashboardIndexRoute
  '/_dashboard-layout/project/$id/': typeof DashboardLayoutProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/signup' | '/dashboard' | '/project/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/signup' | '/dashboard' | '/project/$id'
  id:
    | '__root__'
    | '/'
    | '/_dashboard-layout'
    | '/login/'
    | '/signup/'
    | '/_dashboard-layout/dashboard/'
    | '/_dashboard-layout/project/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardLayoutLazyRoute: typeof DashboardLayoutLazyRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
  SignupIndexRoute: typeof SignupIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard-layout': {
      id: '/_dashboard-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashboardLayoutLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/': {
      id: '/signup/'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard-layout/dashboard/': {
      id: '/_dashboard-layout/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardLayoutDashboardIndexRouteImport
      parentRoute: typeof DashboardLayoutLazyRoute
    }
    '/_dashboard-layout/project/$id/': {
      id: '/_dashboard-layout/project/$id/'
      path: '/project/$id'
      fullPath: '/project/$id'
      preLoaderRoute: typeof DashboardLayoutProjectIdIndexRouteImport
      parentRoute: typeof DashboardLayoutLazyRoute
    }
  }
}

interface DashboardLayoutLazyRouteChildren {
  DashboardLayoutDashboardIndexRoute: typeof DashboardLayoutDashboardIndexRoute
  DashboardLayoutProjectIdIndexRoute: typeof DashboardLayoutProjectIdIndexRoute
}

const DashboardLayoutLazyRouteChildren: DashboardLayoutLazyRouteChildren = {
  DashboardLayoutDashboardIndexRoute: DashboardLayoutDashboardIndexRoute,
  DashboardLayoutProjectIdIndexRoute: DashboardLayoutProjectIdIndexRoute,
}

const DashboardLayoutLazyRouteWithChildren =
  DashboardLayoutLazyRoute._addFileChildren(DashboardLayoutLazyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardLayoutLazyRoute: DashboardLayoutLazyRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
  SignupIndexRoute: SignupIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
